route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'ses'
receivers:
  - name: 'ses'
    email_configs:
      - smarthost: '*****:587' #SMTP endpoint url
        auth_username: 'your username' #SMTP USER NAme
        auth_password: "your password" #Password
        from: 'kdprasad028@gmail.com'
        to: 'drg.durgaprasad028@gmail.com'
        headers:
          subject: 'Prometheus Mail Alerts'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']

